[project]
name = "flyaicv2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepface>=0.0.97",
    "mediapipe>=0.10.31",
    "opencv-python>=4.12.0.88",
    "tf-keras>=2.20.1",
]
